name: Deploy website to Heroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      #faire git clone du projet pour qu'on puisse détaillé
      - uses: actions/checkout@v2
      #linter
      - uses: michaelw90/PHP-Lint@master