name: Deploy website to Heroku
on:
  push:
    branches:
      - master
job:
  deploy:
    run-on: ubuntu-latest
    steps:
      #faire git clone du projet pour qu'on puisse détaillé
      - uses: actions/checkout@v2
      #linter
      - uses: michaelw90/PHP-Lint@master